CREATE TABLE CAD_AUDITORIA 
(
  AUDITORIA_ID NUMBER NOT NULL 
, DOMINIO VARCHAR2(30 CHAR) 
, ACAO VARCHAR2(255 BYTE) 
, DE CLOB 
, PARA CLOB 
, USUARIO VARCHAR2(25 CHAR) 
, ENTIDADE VARCHAR2(70 CHAR) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_AUDITORIA PRIMARY KEY 
  (
    AUDITORIA_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_AUDITORIA ON CAD_AUDITORIA (AUDITORIA_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (DE) STORE AS SYS_LOB0000021887C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (PARA) STORE AS SYS_LOB0000021887C00005$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE CAD_PARAMETRO 
(
  ID_PARAMETRO NUMBER NOT NULL 
, NM_PARAMETRO VARCHAR2(100 BYTE) NOT NULL 
, VL_PARAMETRO VARCHAR2(255 CHAR) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_PARAMETRO PRIMARY KEY 
  (
    ID_PARAMETRO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_PARAMETRO ON CAD_PARAMETRO (ID_PARAMETRO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_PERFIL 
(
  ID_PREFIL NUMBER NOT NULL 
, DS_SRC_PERFIL VARCHAR2(10 BYTE) NOT NULL 
, NM_PERFIL VARCHAR2(100 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_PERFIL PRIMARY KEY 
  (
    ID_PREFIL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_PERFIL ON CAD_PERFIL (ID_PREFIL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_REGIAO 
(
  ID_REGIAO NUMBER NOT NULL 
, NM_REGIAO VARCHAR2(70 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_REGIAO PRIMARY KEY 
  (
    ID_REGIAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_REGIAO ON CAD_REGIAO (ID_REGIAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_VARIAVEL 
(
  ID_CAD_VARIAVEL NUMBER NOT NULL 
, NM_VARIAVEL VARCHAR2(50 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_VARIAVEL PRIMARY KEY 
  (
    ID_CAD_VARIAVEL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_VARIAVEL ON CAD_VARIAVEL (ID_CAD_VARIAVEL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_TIPO_CAMPO 
(
  ID_MD_TIPO_CAMPO NUMBER NOT NULL 
, DS_TIPO_CAMPO VARCHAR2(100 BYTE) NOT NULL 
, DS_MASCARA VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_TIPO_CAMPO PRIMARY KEY 
  (
    ID_MD_TIPO_CAMPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_TIPO_CAMPO ON MD_TIPO_CAMPO (ID_MD_TIPO_CAMPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_TIPO_REGRA 
(
  ID_MD_TIPO_REGRA NUMBER NOT NULL 
, DS_TIPO_REGRA VARCHAR2(25 CHAR) NOT NULL 
, DS_NOME VARCHAR2(40 CHAR) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) NOT NULL 
, DT_ATUALIZACAO DATE NOT NULL 
, DT_INCLUSAO DATE 
, CONSTRAINT PK_MD_TIPO_REGRA PRIMARY KEY 
  (
    ID_MD_TIPO_REGRA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_TIPO_REGRA ON MD_TIPO_REGRA (ID_MD_TIPO_REGRA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_TIPO_SITUACAO 
(
  ID_MD_TIPO_SITUACAO NUMBER NOT NULL 
, DS_SITUACAO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_TIPO_SITUACAO PRIMARY KEY 
  (
    ID_MD_TIPO_SITUACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_TIPO_SITUACAO ON MD_TIPO_SITUACAO (ID_MD_TIPO_SITUACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_ABRANGENCIA_AVISO 
(
  ID_TIPO_ABRANGENCIA_AVISO NUMBER NOT NULL 
, DS_ABRANGENCIA_AVISO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_ABRANGENCIA_AVISO PRIMARY KEY 
  (
    ID_TIPO_ABRANGENCIA_AVISO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_ABRANGENCIA_AVISO ON TIPO_ABRANGENCIA_AVISO (ID_TIPO_ABRANGENCIA_AVISO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_ACAO 
(
  ID_TIPO_ACAO NUMBER NOT NULL 
, SRC_ACAO VARCHAR2(20 BYTE) NOT NULL 
, NM_ACAO VARCHAR2(200 BYTE) NOT NULL 
, DS_ACAO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_ACAO PRIMARY KEY 
  (
    ID_TIPO_ACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_ACAO ON TIPO_ACAO (ID_TIPO_ACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_AVISO 
(
  ID_TIPO_AVISO NUMBER NOT NULL 
, DS_TIPO_AVISO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_AVISO PRIMARY KEY 
  (
    ID_TIPO_AVISO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_AVISO ON TIPO_AVISO (ID_TIPO_AVISO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_CONCLUSO 
(
  ID_TIPO_CONCLUSO NUMBER NOT NULL 
, DS_TIPO_CONCLUSO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_CONCLUSO PRIMARY KEY 
  (
    ID_TIPO_CONCLUSO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_CONCLUSO ON TIPO_CONCLUSO (ID_TIPO_CONCLUSO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_INF_ARQUIVO 
(
  ID_TIPO_INFORMACAO_ARQ NUMBER NOT NULL 
, DS_TIPO_INFORMACAO_ARQ VARCHAR2(100 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_INF_ARQUIVO PRIMARY KEY 
  (
    ID_TIPO_INFORMACAO_ARQ 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_INF_ARQUIVO ON TIPO_INF_ARQUIVO (ID_TIPO_INFORMACAO_ARQ ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_LOCAL 
(
  ID_TIPO_LOCAL NUMBER NOT NULL 
, NM_LOCAL VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_LOCAL PRIMARY KEY 
  (
    ID_TIPO_LOCAL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_LOCAL ON TIPO_LOCAL (ID_TIPO_LOCAL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_MOTIVO_BAIXA 
(
  ID_TPO_MOTIVO_BAIXA NUMBER NOT NULL 
, DS_TIPOI_BAIXA VARCHAR2(100 CHAR) NOT NULL 
, NM_FLUXO VARCHAR2(40 CHAR) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_MOTIVO_BAIXA PRIMARY KEY 
  (
    ID_TPO_MOTIVO_BAIXA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_MOTIVO_BAIXA ON TIPO_MOTIVO_BAIXA (ID_TPO_MOTIVO_BAIXA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_NATUREZA_PRISAO 
(
  ID_TIPO_NATUREZA_PRISAO NUMBER NOT NULL 
, DS_TIPO_NATUREZA VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_NATUREZA_PRISAO PRIMARY KEY 
  (
    ID_TIPO_NATUREZA_PRISAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_NATUREZA_PRISAO ON TIPO_NATUREZA_PRISAO (ID_TIPO_NATUREZA_PRISAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_PERIODICIDADE 
(
  ID_TIPO_PERIODICIDADE NUMBER NOT NULL 
, DS_PERIODICIDADE VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_PERIODICIDADE PRIMARY KEY 
  (
    ID_TIPO_PERIODICIDADE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_PERIODICIDADE ON TIPO_PERIODICIDADE (ID_TIPO_PERIODICIDADE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_SITUACAO 
(
  ID_TIPO_SITUACAO NUMBER NOT NULL 
, DS_SITUACAO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_SITUACAO PRIMARY KEY 
  (
    ID_TIPO_SITUACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_SITUACAO ON TIPO_SITUACAO (ID_TIPO_SITUACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_USUARIO 
(
  ID_USUARIO NUMBER NOT NULL 
, FK_USUARIO_RELACAO NUMBER 
, FK_PERFIL NUMBER 
, CD_USUARIO VARCHAR2(25 BYTE) NOT NULL 
, NM_USUARIO VARCHAR2(200 BYTE) 
, DS_TELEFONE VARCHAR2(18 BYTE) 
, DS_MATRICULA VARCHAR2(100 BYTE) 
, NM_EMAIL VARCHAR2(255 BYTE) 
, CD_CNJ VARCHAR2(50 BYTE) 
, SAJPG_CDUSUARIO NUMBER 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_USUARIO PRIMARY KEY 
  (
    ID_USUARIO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_USUARIO ON CAD_USUARIO (ID_USUARIO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_CIRCUNSCRICAO 
(
  ID_CIRCUNSCRICAO NUMBER NOT NULL 
, FK_REGIAO NUMBER 
, NM_CIRCUNSCRICAO VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_CIRCUNSCRICAO PRIMARY KEY 
  (
    ID_CIRCUNSCRICAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_CIRCUNSCRICAO ON CAD_CIRCUNSCRICAO (ID_CIRCUNSCRICAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_CAMPO 
(
  ID_MD_CAMPO NUMBER NOT NULL 
, FK_TIPO_CAMPO NUMBER NOT NULL 
, FK_MD_CAMPO NUMBER 
, DS_CODIGO VARCHAR2(100 BYTE) NOT NULL 
, NM_CAMPO VARCHAR2(100 BYTE) NOT NULL 
, DS_ROTULO VARCHAR2(4000 BYTE) NOT NULL 
, DS_NR_PERGUNTA_CNJ VARCHAR2(10 BYTE) 
, DS_AJUDA VARCHAR2(4000 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_CAMPO PRIMARY KEY 
  (
    ID_MD_CAMPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_CAMPO ON MD_CAMPO (ID_MD_CAMPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_FORMULARIO 
(
  ID_MD_FORMULARIO NUMBER NOT NULL 
, FK_MD_TIPO_SITUACAO NUMBER NOT NULL 
, DS_CODIGO VARCHAR2(100 BYTE) NOT NULL 
, DS_NOME VARCHAR2(200 BYTE) NOT NULL 
, DS_ROTULO VARCHAR2(4000 BYTE) NOT NULL 
, DS_AJUDA VARCHAR2(4000 BYTE) NOT NULL 
, DS_SRC_FORMULARIO VARCHAR2(25 BYTE) NOT NULL 
, NR_VERSAO NUMBER NOT NULL 
, NR_INSTANCIA NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_FORMULARIO PRIMARY KEY 
  (
    ID_MD_FORMULARIO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_FORMULARIO ON MD_FORMULARIO (ID_MD_FORMULARIO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_PERFIL_ACAO 
(
  ID_PERFIL_ACAO NUMBER NOT NULL 
, FK_ACAO NUMBER NOT NULL 
, FK_PERFIL NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_PERFIL_ACAO PRIMARY KEY 
  (
    ID_PERFIL_ACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_PERFIL_ACAO ON CAD_PERFIL_ACAO (ID_PERFIL_ACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_AVISO_ESTRUTURA 
(
  ID_AVISO_ESTRUTURA NUMBER NOT NULL 
, FK_TIPO_AVISO NUMBER NOT NULL 
, NM_AVISO_ESTRUTURA VARCHAR2(100 BYTE) 
, DS_CONTEUDO VARCHAR2(4000 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_AVISO_ESTRUTURA PRIMARY KEY 
  (
    ID_AVISO_ESTRUTURA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_AVISO_ESTRUTURA ON CAD_AVISO_ESTRUTURA (ID_AVISO_ESTRUTURA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_VARIAVEL_TIPO_AVISO 
(
  ID_CAD_VARIAVEL_TIPO_AVISO NUMBER NOT NULL 
, FK_VARIAVEL NUMBER NOT NULL 
, FK_TIPO_AVISO NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_VARIAVEL_TIPO_AVISO PRIMARY KEY 
  (
    ID_CAD_VARIAVEL_TIPO_AVISO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_VARIAVEL_TIPO_AVISO ON CAD_VARIAVEL_TIPO_AVISO (ID_CAD_VARIAVEL_TIPO_AVISO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_ARQ_INTEGRACAO_CNJ 
(
  ID_ARQ_INTEGRACAO_CNJ NUMBER NOT NULL 
, FK_TIPO_INFORMACAO_ARQ NUMBER NOT NULL 
, NR_MES NUMBER(2, 0) 
, NR_ANO NUMBER(4, 0) 
, NR_LOTE NUMBER 
, NM_PATH VARCHAR2(255 BYTE) 
, DT_GERACAO DATE 
, DT_FINALIZACAO DATE 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_ARQ_INTEGRACAO_CNJ PRIMARY KEY 
  (
    ID_ARQ_INTEGRACAO_CNJ 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_ARQ_INTEGRACAO_CNJ ON CAD_ARQ_INTEGRACAO_CNJ (ID_ARQ_INTEGRACAO_CNJ ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_USUARIO_ACAO 
(
  ID_USUARIO_ACAO NUMBER NOT NULL 
, FK_TIPO_ACAO NUMBER NOT NULL 
, FK_USUARIO NUMBER NOT NULL 
, FL_PERMITIDO CHAR(1 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_USUARIO_ACAO PRIMARY KEY 
  (
    ID_USUARIO_ACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_USUARIO_ACAO ON CAD_USUARIO_ACAO (ID_USUARIO_ACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_COMARCA 
(
  ID_COMARCA NUMBER NOT NULL 
, FK_CIRCUNSCRICAO NUMBER 
, NM_COMARCA VARCHAR2(100 CHAR) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_COMARCA PRIMARY KEY 
  (
    ID_COMARCA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_COMARCA ON CAD_COMARCA (ID_COMARCA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_SECAO 
(
  ID_TIPO_SECAO NUMBER(10, 0) NOT NULL 
, FK_FORMULARIO NUMBER NOT NULL 
, DS_CODIGO VARCHAR2(100 BYTE) NOT NULL 
, DS_NOME VARCHAR2(100 BYTE) NOT NULL 
, DS_ROTULO VARCHAR2(4000 BYTE) NOT NULL 
, DS_AJUDA VARCHAR2(4000 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_SECAO PRIMARY KEY 
  (
    ID_TIPO_SECAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_SECAO ON MD_SECAO (ID_TIPO_SECAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_CONFIG_AVISO 
(
  ID_CONFIG_AVISO NUMBER NOT NULL 
, FK_AVISO_ESTRUTURA NUMBER 
, FK_TIPO_PERIODICIDADE NUMBER NOT NULL 
, FK_TIPO_ABRANGENCIA NUMBER NOT NULL 
, NM_TITULO VARCHAR2(100 CHAR) 
, DS_RESUMO VARCHAR2(255 CHAR) 
, VL_PERIODICIDADE VARCHAR2(100 CHAR) 
, VL_ABRAN_ENVIO VARCHAR2(255 CHAR) 
, FL_GERAR_HIST_FORM CHAR(1 BYTE) DEFAULT 'N' 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_CONFIG_AVISO PRIMARY KEY 
  (
    ID_CONFIG_AVISO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_CONFIG_AVISO ON CAD_CONFIG_AVISO (ID_CONFIG_AVISO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORO 
(
  FORO_ID NUMBER NOT NULL 
, FK_COMARCA NUMBER 
, NM_FORO VARCHAR2(100 BYTE) 
, NM_ENTRANCIA VARCHAR2(50 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORO PRIMARY KEY 
  (
    FORO_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORO ON CAD_FORO (FORO_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_GRUPO 
(
  ID_MD_GRUPO NUMBER(10, 0) NOT NULL 
, FK_MD_SECAO NUMBER(10, 0) NOT NULL 
, DS_CODIGO VARCHAR2(100 BYTE) NOT NULL 
, DS_NOME VARCHAR2(100 BYTE) NOT NULL 
, DS_ROTULO VARCHAR2(4000 BYTE) NOT NULL 
, DS_AJUDA VARCHAR2(4000 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_MD_GRUPO PRIMARY KEY 
  (
    ID_MD_GRUPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_GRUPO ON MD_GRUPO (ID_MD_GRUPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE TIPO_PROCESSAMENTO 
(
  ID_TIPO_PROCESSAMENTO NUMBER NOT NULL 
, DS_TIPO_PROCESSAMENTO VARCHAR2(100 BYTE) 
, CONFIG_AVISO_ID NUMBER 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_TIPO_PROCESSAMENTO PRIMARY KEY 
  (
    ID_TIPO_PROCESSAMENTO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_TIPO_PROCESSAMENTO ON TIPO_PROCESSAMENTO (ID_TIPO_PROCESSAMENTO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_UNIDADE 
(
  ID_CAD_UNIDADE NUMBER NOT NULL 
, FK_CAD_FORO NUMBER(10, 0) NOT NULL 
, FK_TIPO_LOCAL NUMBER NOT NULL 
, FK_CAD_USUARIO NUMBER(10, 0) NOT NULL 
, NM_UNIDADE VARCHAR2(100 BYTE) NOT NULL 
, CD_CNJ VARCHAR2(50 BYTE) 
, SAJPG_CDFORO_ID NUMBER 
, SAJPG_CDVARA_ID NUMBER 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, DT_CRIACAO DATE NOT NULL 
, DT_FIM DATE 
, DS_TELEFONE_INST VARCHAR2(18 BYTE) 
, NM_EMAIL_INST VARCHAR2(255 BYTE) 
, DS_MOTIVO VARCHAR2(2000 BYTE) 
, CONSTRAINT PK_CAD_UNIDADE PRIMARY KEY 
  (
    ID_CAD_UNIDADE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_UNIDADE ON CAD_UNIDADE (ID_CAD_UNIDADE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_HISTORICO_PROCESSAMENTO 
(
  ID_HISTORICO_PROCES NUMBER NOT NULL 
, FK_TIPO_PROCESSAMENTO NUMBER NOT NULL 
, NR_ANO NUMBER(4, 0) 
, NR_MES NUMBER(2, 0) 
, DT_INICIO DATE 
, DT_FIM DATE 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_HIST_PROCESSAMENTO PRIMARY KEY 
  (
    ID_HISTORICO_PROCES 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_HIST_PROCESSAMENTO ON CAD_HISTORICO_PROCESSAMENTO (ID_HISTORICO_PROCES ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_ESTAB_PRISIONAL 
(
  ID_ESTAB_PRISIONAL NUMBER NOT NULL 
, FK_UNIDADE NUMBER 
, NM_ESTAB_PRISIONAL VARCHAR2(200 BYTE) 
, NM_MUNICIPIO VARCHAR2(100 BYTE) 
, CD_UF CHAR(1 BYTE) 
, FL_PRISIONAL CHAR(1 BYTE) DEFAULT 'S' 
, FL_INTERNACAO CHAR(1 BYTE) DEFAULT 'S' 
, SAJPG_CDLOCAL_PRISAO_ID NUMBER 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_ESTAB_PRISIONAL PRIMARY KEY 
  (
    ID_ESTAB_PRISIONAL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_ESTAB_PRISIONAL ON CAD_ESTAB_PRISIONAL (ID_ESTAB_PRISIONAL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORMULARIO 
(
  ID_CAD_FORMULARIO NUMBER NOT NULL 
, FK_UNIDADE NUMBER 
, FK_USUARIO_APROV NUMBER 
, FK_USUARIO_PREENC NUMBER 
, FK_TIPO_SITUACAO NUMBER NOT NULL 
, FK_MD_FORMULARIO NUMBER NOT NULL 
, NR_MES NUMBER 
, NR_ANO NUMBER 
, DT_FECHAMENTO DATE 
, DT_APROVACAO DATE 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORMULARIO PRIMARY KEY 
  (
    ID_CAD_FORMULARIO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORMULARIO ON CAD_FORMULARIO (ID_CAD_FORMULARIO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORM_VINCULACAO 
(
  ID_FORM_VINCULACAO NUMBER(18, 0) NOT NULL 
, FK_CAD_UNIDADE NUMBER NOT NULL 
, FK_MD_FORMULARIO NUMBER NOT NULL 
, DS_REGRAS VARCHAR2(2000 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORM_VINCULACAO PRIMARY KEY 
  (
    ID_FORM_VINCULACAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORM_VINCULACAO ON CAD_FORM_VINCULACAO (ID_FORM_VINCULACAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_PERMISSAO_UNID_TEMP 
(
  ID_PERM_UNID_TEMP NUMBER NOT NULL 
, FK_UNIDADE NUMBER 
, FK_USUARIO NUMBER 
, DT_VALIDADE DATE 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_PERMISSAO_UNID_TEMP PRIMARY KEY 
  (
    ID_PERM_UNID_TEMP 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_PERMISSAO_UNID_TEMP ON CAD_PERMISSAO_UNID_TEMP (ID_PERM_UNID_TEMP ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_PROCESSO_CONCLUSO 
(
  ID_PROCESSO_CONCLUS0 NUMBER NOT NULL 
, FK_FORMULARIO NUMBER NOT NULL 
, FK_USUARIO NUMBER NOT NULL 
, FK_UNIDADE NUMBER NOT NULL 
, FK_TIPO_CONCLUSO NUMBER NOT NULL 
, NR_MES NUMBER(2, 0) NOT NULL 
, NR_ANO NUMBER(4, 0) NOT NULL 
, NR_PROCESSO NUMBER NOT NULL 
, NR_ANO_PROCESSO NUMBER(4, 0) NOT NULL 
, DT_BAIXA DATE 
, SAJPG_CDPROCESSO VARCHAR2(20 BYTE) 
, SAJPG_BASE_ORIGEM_ID VARCHAR2(10 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_PROCESSO_CONCLUSO PRIMARY KEY 
  (
    ID_PROCESSO_CONCLUS0 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_PROCESSO_CONCLUSO ON CAD_PROCESSO_CONCLUSO (ID_PROCESSO_CONCLUS0 ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_UNIDADE_ANEXA 
(
  ID_UNIDADE_ANEXA NUMBER NOT NULL 
, FK_UNIDADE NUMBER 
, NM_UNIDADE_ANEXA VARCHAR2(100 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_UNIDADE_ANEXA PRIMARY KEY 
  (
    ID_UNIDADE_ANEXA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_UNIDADE_ANEXA ON CAD_UNIDADE_ANEXA (ID_UNIDADE_ANEXA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_UNIDADE_AREA 
(
  ID_UNIDADE_AREA NUMBER NOT NULL 
, FK_CAD_UNIDADE NUMBER 
, DS_UNIDADE_AREA VARCHAR2(100 BYTE) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_UNIDADE_AREA PRIMARY KEY 
  (
    ID_UNIDADE_AREA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_UNIDADE_AREA ON CAD_UNIDADE_AREA (ID_UNIDADE_AREA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_UNIDADE_ENDERECO 
(
  ID_UNIDADE_ENDERECO NUMBER NOT NULL 
, FK_UNIDADE NUMBER 
, NM_LOGRADOURO VARCHAR2(255 BYTE) 
, NM_COMPLEMENTO VARCHAR2(255 BYTE) 
, NM_BAIRRO VARCHAR2(50 BYTE) 
, CD_CEP VARCHAR2(18 BYTE) 
, NM_MUNICIPIO VARCHAR2(100 BYTE) 
, CD_UF CHAR(1 BYTE) 
, CD_TELEFONE VARCHAR2(18 BYTE) 
, NM_EMAIL VARCHAR2(255 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_UNIDADE_ENDERECO PRIMARY KEY 
  (
    ID_UNIDADE_ENDERECO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_UNIDADE_ENDERECO ON CAD_UNIDADE_ENDERECO (ID_UNIDADE_ENDERECO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_UNIDADE_FORO_RECURSAL 
(
  ID_UNIDADE_FORO_RECURSAL NUMBER NOT NULL 
, FK_UNIDADE NUMBER NOT NULL 
, FK_FORO NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_UNIDADE_FORO_RECURSAL PRIMARY KEY 
  (
    ID_UNIDADE_FORO_RECURSAL 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_UNIDADE_FORO_RECURSAL ON CAD_UNIDADE_FORO_RECURSAL (ID_UNIDADE_FORO_RECURSAL ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_REU_PROVISORIO 
(
  ID_REU_PROVISORIO NUMBER NOT NULL 
, FK_MOTIVO_BAIXA NUMBER 
, FK_UNIDADE NUMBER 
, FK_TIPO_FORMULARIO NUMBER 
, FK_ESTAB_PRISIONAL NUMBER 
, FK_USUARIO_MAG NUMBER 
, NM_REU_PROV VARCHAR2(100 BYTE) 
, NM_MAE_REU_PROV VARCHAR2(100 BYTE) 
, DT_PRISAO DATE 
, TP_SEXO CHAR(1 BYTE) 
, DT_BAIXA DATE 
, DS_RELATORIO_CGJ VARCHAR2(100 BYTE) 
, DT_LEVADO_MAGISTRADO DATE 
, SAJPG_CD_PESSOA_ID NUMBER(10, 0) 
, SAJPG_BASE_ORIGEM_ID VARCHAR2(10 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_REU_PROVISORIO PRIMARY KEY 
  (
    ID_REU_PROVISORIO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_REU_PROVISORIO ON CAD_REU_PROVISORIO (ID_REU_PROVISORIO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_AVISO 
(
  ID_AVISO NUMBER NOT NULL 
, FK_CONFIG_AVISO NUMBER 
, FK_CAD_FORMULARIO NUMBER 
, FK_USUARIO NUMBER 
, VL_VARIAVEIS VARCHAR2(255 BYTE) 
, DT_ENVIO DATE 
, FL_LIDO CHAR(1 BYTE) DEFAULT 'N' 
, DT_LIDO DATE 
, FL_EXCLUIDO CHAR(1 BYTE) DEFAULT 'N' 
, DT_EXCLUIDO DATE 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_AVISO PRIMARY KEY 
  (
    ID_AVISO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_AVISO ON CAD_AVISO (ID_AVISO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORMULARIO_ARQUIVO 
(
  ID_CAD_FORMULARIO_ARQUIVO NUMBER NOT NULL 
, FK_CAD_ARQ_INTEGRACAO NUMBER NOT NULL 
, FK_CAD_FORMULARIO NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORMULARIO_ARQUIVO PRIMARY KEY 
  (
    ID_CAD_FORMULARIO_ARQUIVO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORMULARIO_ARQUIVO ON CAD_FORMULARIO_ARQUIVO (ID_CAD_FORMULARIO_ARQUIVO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORMULARIO_HIST 
(
  ID_CAD_FORMULARIO_HIST NUMBER NOT NULL 
, FK_CAD_FORMULARIO NUMBER NOT NULL 
, FK_TIPO_SITUACAO NUMBER NOT NULL 
, FK_USUARIO NUMBER 
, DT_CRIACAO DATE NOT NULL 
, XML_ANTERIOR CLOB 
, XML_NOVO CLOB 
, DS_COMENTARIO VARCHAR2(2000 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORMULARIO_HIST PRIMARY KEY 
  (
    ID_CAD_FORMULARIO_HIST 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORMULARIO_HIST ON CAD_FORMULARIO_HIST (ID_CAD_FORMULARIO_HIST ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (XML_ANTERIOR) STORE AS SYS_LOB0000021913C00006$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (XML_NOVO) STORE AS SYS_LOB0000021913C00007$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE CAD_FORM_TIPO_REGRA 
(
  ID_CAD_FORM_TIPO_REGRA NUMBER NOT NULL 
, FK_CAD_FORMULARIO NUMBER NOT NULL 
, FK_MD_TIPO_REGRA NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORM_TIPO_REGRA PRIMARY KEY 
  (
    ID_CAD_FORM_TIPO_REGRA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORM_TIPO_REGRA ON CAD_FORM_TIPO_REGRA (ID_CAD_FORM_TIPO_REGRA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_SECAO 
(
  ID_CAD_SECAO NUMBER(10, 0) NOT NULL 
, FK_MD_SECAO NUMBER(10, 0) NOT NULL 
, FK_CAD_FORMULARIO1 NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_SECAO PRIMARY KEY 
  (
    ID_CAD_SECAO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_SECAO ON CAD_SECAO (ID_CAD_SECAO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_FORM_VINC_TIPO_REGRA 
(
  ID_FORM_VINC_TIPO_REGRA NUMBER(18, 0) NOT NULL 
, FK_FORMULARIO_VINCULACAO_ID NUMBER(18, 0) NOT NULL 
, TIPO_REGRA_ID NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_FORM_VINC_TIPO_REGRA PRIMARY KEY 
  (
    ID_FORM_VINC_TIPO_REGRA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_FORM_VINC_TIPO_REGRA ON CAD_FORM_VINC_TIPO_REGRA (ID_FORM_VINC_TIPO_REGRA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE MD_GRUPO_CAMPO 
(
  ID_MD_GRUPO_CAMPO NUMBER NOT NULL 
, FK_ID_CAMPO NUMBER NOT NULL 
, FK_ID_GRUPO NUMBER(10, 0) NOT NULL 
, FK_TIPO_REGRA NUMBER 
, FK_UNIDADE_AREA NUMBER 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, DS_FORMULA VARCHAR2(1000 BYTE) 
, NR_NIVEL NUMBER(10, 0) NOT NULL 
, NR_ORDEM NUMBER(10, 0) NOT NULL 
, CONSTRAINT PK_MD_GRUPO_CAMPO PRIMARY KEY 
  (
    ID_MD_GRUPO_CAMPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_MD_GRUPO_CAMPO ON MD_GRUPO_CAMPO (ID_MD_GRUPO_CAMPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_REU_PROVISORIO_HIST 
(
  ID_REU_PROVISORIO_HIST NUMBER NOT NULL 
, ID_TIPO_NATUREZA_PRISAO NUMBER NOT NULL 
, NR_MES NUMBER(2, 0) NOT NULL 
, NR_ANO NUMBER(4, 0) NOT NULL 
, NR_PROCESSO VARCHAR2(50 BYTE) 
, NR_CONTROLE_ORDEM VARCHAR2(20 BYTE) 
, DT_ULT_MOV DATE 
, DS_CONTEUDO_ULT_MOV VARCHAR2(1000 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, ID_REU_PROVISORIO NUMBER NOT NULL 
, CONSTRAINT CAD_REU_PROVISORIO_HIST_PK PRIMARY KEY 
  (
    ID_REU_PROVISORIO_HIST 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CAD_REU_PROVISORIO_HIST_PK ON CAD_REU_PROVISORIO_HIST (ID_REU_PROVISORIO_HIST ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_GRUPO 
(
  ID_CAD_GRUPO NUMBER(10, 0) NOT NULL 
, FK_MD_GRUPO NUMBER(10, 0) NOT NULL 
, FK_CAD_SECAO NUMBER(10, 0) NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, MD_SECAO_ID_TIPO_SECAO NUMBER(10, 0) NOT NULL 
, CONSTRAINT PK_CAD_GRUPO PRIMARY KEY 
  (
    ID_CAD_GRUPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_GRUPO ON CAD_GRUPO (ID_CAD_GRUPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_CAMPO 
(
  ID_CAD_CAMPO NUMBER NOT NULL 
, FK_MD_CAMPO NUMBER NOT NULL 
, FK_CAD_GRUPO NUMBER(10, 0) NOT NULL 
, FK_CAD_CAMPO NUMBER 
, FK_USUARIO NUMBER 
, VL_CAMPO VARCHAR2(2000 BYTE) 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_CAMPO PRIMARY KEY 
  (
    ID_CAD_CAMPO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_CAMPO ON CAD_CAMPO (ID_CAD_CAMPO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

CREATE TABLE CAD_CAMPO_UNI_AREA 
(
  FK_CAD_CAMPO NUMBER 
, FK_CAD_UNIDADE_AREA NUMBER 
, ID_CAD_CAMPO_UNI_AREA NUMBER NOT NULL 
, TP_SITUACAO CHAR(1 BYTE) DEFAULT 'A' NOT NULL 
, DT_INCLUSAO DATE NOT NULL 
, DT_ATUALIZACAO DATE 
, CONSTRAINT PK_CAD_CAMPO_UNI_AREA PRIMARY KEY 
  (
    ID_CAD_CAMPO_UNI_AREA 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_CAD_CAMPO_UNI_AREA ON CAD_CAMPO_UNI_AREA (ID_CAD_CAMPO_UNI_AREA ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE CAD_ARQ_INTEGRACAO_CNJ
ADD CONSTRAINT FK_ARQ_INTEG_TP_INF_ARQUIVO FOREIGN KEY
(
  FK_TIPO_INFORMACAO_ARQ 
)
REFERENCES TIPO_INF_ARQUIVO
(
  ID_TIPO_INFORMACAO_ARQ 
)
ENABLE;

ALTER TABLE CAD_AVISO
ADD CONSTRAINT FK_AVISO_CONFIG_AVISO FOREIGN KEY
(
  FK_CONFIG_AVISO 
)
REFERENCES CAD_CONFIG_AVISO
(
  ID_CONFIG_AVISO 
)
ENABLE;

ALTER TABLE CAD_AVISO
ADD CONSTRAINT FK_AVISO_FORMULARIO FOREIGN KEY
(
  FK_CAD_FORMULARIO 
)
REFERENCES CAD_FORMULARIO
(
  ID_CAD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_AVISO
ADD CONSTRAINT FK_AVISO_USUARIO FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_AVISO_ESTRUTURA
ADD CONSTRAINT FK_AVISO_ESTR_TIPO_AVISO FOREIGN KEY
(
  FK_TIPO_AVISO 
)
REFERENCES TIPO_AVISO
(
  ID_TIPO_AVISO 
)
ENABLE;

ALTER TABLE CAD_CAMPO
ADD CONSTRAINT FK_CAMPO_CAMPO FOREIGN KEY
(
  FK_CAD_CAMPO 
)
REFERENCES CAD_CAMPO
(
  ID_CAD_CAMPO 
)
ENABLE;

ALTER TABLE CAD_CAMPO
ADD CONSTRAINT FK_CAMPO_GRUPO FOREIGN KEY
(
  FK_CAD_GRUPO 
)
REFERENCES CAD_GRUPO
(
  ID_CAD_GRUPO 
)
ENABLE;

ALTER TABLE CAD_CAMPO
ADD CONSTRAINT FK_CAMPO_MD_CAMPO FOREIGN KEY
(
  FK_MD_CAMPO 
)
REFERENCES MD_CAMPO
(
  ID_MD_CAMPO 
)
ENABLE;

ALTER TABLE CAD_CAMPO
ADD CONSTRAINT FK_CAMPO_USUARIO FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_CAMPO_UNI_AREA
ADD CONSTRAINT FK_CAMPO_UNI_AREA_CAMPO FOREIGN KEY
(
  FK_CAD_CAMPO 
)
REFERENCES CAD_CAMPO
(
  ID_CAD_CAMPO 
)
ENABLE;

ALTER TABLE CAD_CAMPO_UNI_AREA
ADD CONSTRAINT FK_CAMPO_UNI_AREA_UNI_AREA FOREIGN KEY
(
  FK_CAD_UNIDADE_AREA 
)
REFERENCES CAD_UNIDADE_AREA
(
  ID_UNIDADE_AREA 
)
ENABLE;

ALTER TABLE CAD_CIRCUNSCRICAO
ADD CONSTRAINT FK_CIRCUNSCRICAO_REGIAO FOREIGN KEY
(
  FK_REGIAO 
)
REFERENCES CAD_REGIAO
(
  ID_REGIAO 
)
ENABLE;

ALTER TABLE CAD_COMARCA
ADD CONSTRAINT FK_COMARCA_CIRCUNSCRICAO FOREIGN KEY
(
  FK_CIRCUNSCRICAO 
)
REFERENCES CAD_CIRCUNSCRICAO
(
  ID_CIRCUNSCRICAO 
)
ENABLE;

ALTER TABLE CAD_CONFIG_AVISO
ADD CONSTRAINT FK_CONFIG_AVISO_ABRANGENCIA FOREIGN KEY
(
  FK_TIPO_ABRANGENCIA 
)
REFERENCES TIPO_ABRANGENCIA_AVISO
(
  ID_TIPO_ABRANGENCIA_AVISO 
)
ENABLE;

ALTER TABLE CAD_CONFIG_AVISO
ADD CONSTRAINT FK_CONFIG_AVISO_ESTRUTURA FOREIGN KEY
(
  FK_AVISO_ESTRUTURA 
)
REFERENCES CAD_AVISO_ESTRUTURA
(
  ID_AVISO_ESTRUTURA 
)
ENABLE;

ALTER TABLE CAD_CONFIG_AVISO
ADD CONSTRAINT FK_CONFIG_AVISO_PERIODICIDADE FOREIGN KEY
(
  FK_TIPO_PERIODICIDADE 
)
REFERENCES TIPO_PERIODICIDADE
(
  ID_TIPO_PERIODICIDADE 
)
ENABLE;

ALTER TABLE CAD_ESTAB_PRISIONAL
ADD CONSTRAINT FK_ESTAB_PRIS_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_MD_FORMULARIO FOREIGN KEY
(
  FK_MD_FORMULARIO 
)
REFERENCES MD_FORMULARIO
(
  ID_MD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_TIPO_SITUACAO FOREIGN KEY
(
  FK_TIPO_SITUACAO 
)
REFERENCES TIPO_SITUACAO
(
  ID_TIPO_SITUACAO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_USUARIO_APR FOREIGN KEY
(
  FK_USUARIO_APROV 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_USUARIO_PREEC FOREIGN KEY
(
  FK_USUARIO_PREENC 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO_ARQUIVO
ADD CONSTRAINT FK_FORM_ARQUIVO_ARQ_INT FOREIGN KEY
(
  FK_CAD_ARQ_INTEGRACAO 
)
REFERENCES CAD_ARQ_INTEGRACAO_CNJ
(
  ID_ARQ_INTEGRACAO_CNJ 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO_ARQUIVO
ADD CONSTRAINT FK_FORM_ARQUIVO_FORM FOREIGN KEY
(
  FK_CAD_FORMULARIO 
)
REFERENCES CAD_FORMULARIO
(
  ID_CAD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO_HIST
ADD CONSTRAINT FK_FORM_HIST_FORMULARIO FOREIGN KEY
(
  FK_CAD_FORMULARIO 
)
REFERENCES CAD_FORMULARIO
(
  ID_CAD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO_HIST
ADD CONSTRAINT FK_FORM_HIST_SITUACAO FOREIGN KEY
(
  FK_TIPO_SITUACAO 
)
REFERENCES TIPO_SITUACAO
(
  ID_TIPO_SITUACAO 
)
ENABLE;

ALTER TABLE CAD_FORMULARIO_HIST
ADD CONSTRAINT FK_FORM_HIST_USUARIO FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_FORM_TIPO_REGRA
ADD CONSTRAINT FK_FORM_TR_FORMULARIO FOREIGN KEY
(
  FK_CAD_FORMULARIO 
)
REFERENCES CAD_FORMULARIO
(
  ID_CAD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_FORM_TIPO_REGRA
ADD CONSTRAINT FK_FORM_TR_MD_TIPO_REGRA FOREIGN KEY
(
  FK_MD_TIPO_REGRA 
)
REFERENCES MD_TIPO_REGRA
(
  ID_MD_TIPO_REGRA 
)
ENABLE;

ALTER TABLE CAD_FORM_VINCULACAO
ADD CONSTRAINT FK_FORM_VINC_FORM FOREIGN KEY
(
  FK_MD_FORMULARIO 
)
REFERENCES MD_FORMULARIO
(
  ID_MD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_FORM_VINCULACAO
ADD CONSTRAINT FK_FORM_VINC_UNID FOREIGN KEY
(
  FK_CAD_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_FORM_VINC_TIPO_REGRA
ADD CONSTRAINT FK_FORM_VINC_TR_MD_TIPO_REGRA FOREIGN KEY
(
  TIPO_REGRA_ID 
)
REFERENCES MD_TIPO_REGRA
(
  ID_MD_TIPO_REGRA 
)
ENABLE;

ALTER TABLE CAD_FORM_VINC_TIPO_REGRA
ADD CONSTRAINT FK_FORM_VINC_TR_VINCULACAO FOREIGN KEY
(
  FK_FORMULARIO_VINCULACAO_ID 
)
REFERENCES CAD_FORM_VINCULACAO
(
  ID_FORM_VINCULACAO 
)
ENABLE;

ALTER TABLE CAD_FORO
ADD CONSTRAINT FK_FORO_COMARCA FOREIGN KEY
(
  FK_COMARCA 
)
REFERENCES CAD_COMARCA
(
  ID_COMARCA 
)
ENABLE;

ALTER TABLE CAD_GRUPO
ADD CONSTRAINT FK_GRUPO_MD_GRUPO FOREIGN KEY
(
  FK_MD_GRUPO 
)
REFERENCES MD_GRUPO
(
  ID_MD_GRUPO 
)
ENABLE;

ALTER TABLE CAD_GRUPO
ADD CONSTRAINT FK_GRUPO_SECAO FOREIGN KEY
(
  FK_CAD_SECAO 
)
REFERENCES CAD_SECAO
(
  ID_CAD_SECAO 
)
ENABLE;

ALTER TABLE CAD_HISTORICO_PROCESSAMENTO
ADD CONSTRAINT FK_HIST_PROC_TP_PROC FOREIGN KEY
(
  FK_TIPO_PROCESSAMENTO 
)
REFERENCES TIPO_PROCESSAMENTO
(
  ID_TIPO_PROCESSAMENTO 
)
ENABLE;

ALTER TABLE CAD_PERFIL_ACAO
ADD CONSTRAINT FK_PERFIL_ACAO_ACAO FOREIGN KEY
(
  FK_ACAO 
)
REFERENCES TIPO_ACAO
(
  ID_TIPO_ACAO 
)
ENABLE;

ALTER TABLE CAD_PERFIL_ACAO
ADD CONSTRAINT FK_PERFIL_ACAO_PERFIL FOREIGN KEY
(
  FK_PERFIL 
)
REFERENCES CAD_PERFIL
(
  ID_PREFIL 
)
ENABLE;

ALTER TABLE CAD_PERMISSAO_UNID_TEMP
ADD CONSTRAINT FK_PERMISSAO_UNID_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_PERMISSAO_UNID_TEMP
ADD CONSTRAINT FK_PERMISSAO_UNID_USUARIO FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_PROCESSO_CONCLUSO
ADD CONSTRAINT FK_PRO_CONCLUSO_FORMULARIO FOREIGN KEY
(
  FK_FORMULARIO 
)
REFERENCES MD_FORMULARIO
(
  ID_MD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_PROCESSO_CONCLUSO
ADD CONSTRAINT FK_PRO_CONCLUSO_TIPO_CONCLUSO FOREIGN KEY
(
  FK_TIPO_CONCLUSO 
)
REFERENCES TIPO_CONCLUSO
(
  ID_TIPO_CONCLUSO 
)
ENABLE;

ALTER TABLE CAD_PROCESSO_CONCLUSO
ADD CONSTRAINT FK_PRO_CONCLUSO_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_PROCESSO_CONCLUSO
ADD CONSTRAINT FK_PRO_CONCLUSO_USUARIO FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO
ADD CONSTRAINT FK_REU_PROVIS_ESTAB_PRISIONAL FOREIGN KEY
(
  FK_ESTAB_PRISIONAL 
)
REFERENCES CAD_ESTAB_PRISIONAL
(
  ID_ESTAB_PRISIONAL 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO
ADD CONSTRAINT FK_REU_PROVIS_MD_FORMULARIO FOREIGN KEY
(
  FK_TIPO_FORMULARIO 
)
REFERENCES MD_FORMULARIO
(
  ID_MD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO
ADD CONSTRAINT FK_REU_PROVIS_TP_MOT_BXA FOREIGN KEY
(
  FK_MOTIVO_BAIXA 
)
REFERENCES TIPO_MOTIVO_BAIXA
(
  ID_TPO_MOTIVO_BAIXA 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO
ADD CONSTRAINT FK_REU_PROVIS_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO
ADD CONSTRAINT FK_REU_PROVIS_USUARIO FOREIGN KEY
(
  FK_USUARIO_MAG 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO_HIST
ADD CONSTRAINT FK_REU_PROVISORIO_HIST_REU FOREIGN KEY
(
  ID_REU_PROVISORIO 
)
REFERENCES CAD_REU_PROVISORIO
(
  ID_REU_PROVISORIO 
)
ENABLE;

ALTER TABLE CAD_REU_PROVISORIO_HIST
ADD CONSTRAINT FK_REU_PROVISORIO_HIST_TIPO FOREIGN KEY
(
  ID_TIPO_NATUREZA_PRISAO 
)
REFERENCES TIPO_NATUREZA_PRISAO
(
  ID_TIPO_NATUREZA_PRISAO 
)
ENABLE;

ALTER TABLE CAD_SECAO
ADD CONSTRAINT FK_SECAO_FORMULARIO FOREIGN KEY
(
  FK_CAD_FORMULARIO1 
)
REFERENCES CAD_FORMULARIO
(
  ID_CAD_FORMULARIO 
)
ENABLE;

ALTER TABLE CAD_SECAO
ADD CONSTRAINT FK_SECAO_MD_SECAO FOREIGN KEY
(
  FK_MD_SECAO 
)
REFERENCES MD_SECAO
(
  ID_TIPO_SECAO 
)
ENABLE;

ALTER TABLE CAD_UNIDADE
ADD CONSTRAINT FK_UNIDADE_FORO FOREIGN KEY
(
  FK_CAD_FORO 
)
REFERENCES CAD_FORO
(
  FORO_ID 
)
ENABLE;

ALTER TABLE CAD_UNIDADE
ADD CONSTRAINT FK_UNIDADE_TIPO_LOCAL FOREIGN KEY
(
  FK_TIPO_LOCAL 
)
REFERENCES TIPO_LOCAL
(
  ID_TIPO_LOCAL 
)
ENABLE;

ALTER TABLE CAD_UNIDADE
ADD CONSTRAINT FK_UNIDADE_USUARIO FOREIGN KEY
(
  FK_CAD_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_UNIDADE_ANEXA
ADD CONSTRAINT FK_UNIDADE_ANEXA_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_UNIDADE_AREA
ADD CONSTRAINT FK_UNIDADE_AREA_UNI FOREIGN KEY
(
  FK_CAD_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_UNIDADE_ENDERECO
ADD CONSTRAINT FK_UNI_ENDERECO_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_UNIDADE_FORO_RECURSAL
ADD CONSTRAINT FK_UNI_FORO_REC_FORO FOREIGN KEY
(
  FK_FORO 
)
REFERENCES CAD_FORO
(
  FORO_ID 
)
ENABLE;

ALTER TABLE CAD_UNIDADE_FORO_RECURSAL
ADD CONSTRAINT FK_UNI_FORO_REC_UNIDADE FOREIGN KEY
(
  FK_UNIDADE 
)
REFERENCES CAD_UNIDADE
(
  ID_CAD_UNIDADE 
)
ENABLE;

ALTER TABLE CAD_USUARIO
ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY
(
  FK_PERFIL 
)
REFERENCES CAD_PERFIL
(
  ID_PREFIL 
)
ENABLE;

ALTER TABLE CAD_USUARIO
ADD CONSTRAINT FK_USUARIO_USUARIO FOREIGN KEY
(
  FK_USUARIO_RELACAO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_USUARIO_ACAO
ADD CONSTRAINT FK_CAD_USUARIO_ACAO_TIPO_ACAO FOREIGN KEY
(
  FK_TIPO_ACAO 
)
REFERENCES TIPO_ACAO
(
  ID_TIPO_ACAO 
)
ENABLE;

ALTER TABLE CAD_USUARIO_ACAO
ADD CONSTRAINT FK_CAD_USUARIO_ACAO_USU FOREIGN KEY
(
  FK_USUARIO 
)
REFERENCES CAD_USUARIO
(
  ID_USUARIO 
)
ENABLE;

ALTER TABLE CAD_VARIAVEL_TIPO_AVISO
ADD CONSTRAINT FK_VARIAVEL_TP_AVISO_AVISO FOREIGN KEY
(
  FK_TIPO_AVISO 
)
REFERENCES TIPO_AVISO
(
  ID_TIPO_AVISO 
)
ENABLE;

ALTER TABLE CAD_VARIAVEL_TIPO_AVISO
ADD CONSTRAINT FK_VARIAVEL_TP_AVISO_VARIAVEL FOREIGN KEY
(
  FK_VARIAVEL 
)
REFERENCES CAD_VARIAVEL
(
  ID_CAD_VARIAVEL 
)
ENABLE;

ALTER TABLE MD_CAMPO
ADD CONSTRAINT FK_MD_CAMPO_MD_CAMPO FOREIGN KEY
(
  FK_MD_CAMPO 
)
REFERENCES MD_CAMPO
(
  ID_MD_CAMPO 
)
ENABLE;

ALTER TABLE MD_CAMPO
ADD CONSTRAINT FK_MD_CAMPO_MD_TIPO_CAMPO FOREIGN KEY
(
  FK_TIPO_CAMPO 
)
REFERENCES MD_TIPO_CAMPO
(
  ID_MD_TIPO_CAMPO 
)
ENABLE;

ALTER TABLE MD_FORMULARIO
ADD CONSTRAINT FK_MD_FORM_TIPO_SITUACAO FOREIGN KEY
(
  FK_MD_TIPO_SITUACAO 
)
REFERENCES MD_TIPO_SITUACAO
(
  ID_MD_TIPO_SITUACAO 
)
ENABLE;

ALTER TABLE MD_GRUPO
ADD CONSTRAINT FK_MD_GRUPO_MD_SECAO FOREIGN KEY
(
  FK_MD_SECAO 
)
REFERENCES MD_SECAO
(
  ID_TIPO_SECAO 
)
ENABLE;

ALTER TABLE MD_GRUPO_CAMPO
ADD CONSTRAINT FK_GRUPO_CAMPO_CAMPO FOREIGN KEY
(
  FK_ID_CAMPO 
)
REFERENCES MD_CAMPO
(
  ID_MD_CAMPO 
)
ENABLE;

ALTER TABLE MD_GRUPO_CAMPO
ADD CONSTRAINT FK_GRUPO_CAMPO_GRUPO FOREIGN KEY
(
  FK_ID_GRUPO 
)
REFERENCES MD_GRUPO
(
  ID_MD_GRUPO 
)
ENABLE;

ALTER TABLE MD_GRUPO_CAMPO
ADD CONSTRAINT FK_GRUPO_CAMPO_TP_REGRA FOREIGN KEY
(
  FK_TIPO_REGRA 
)
REFERENCES MD_TIPO_REGRA
(
  ID_MD_TIPO_REGRA 
)
ENABLE;

ALTER TABLE MD_GRUPO_CAMPO
ADD CONSTRAINT FK_GRUPO_CAMPO_UNI_AREA FOREIGN KEY
(
  FK_UNIDADE_AREA 
)
REFERENCES CAD_UNIDADE_AREA
(
  ID_UNIDADE_AREA 
)
ENABLE;

ALTER TABLE MD_SECAO
ADD CONSTRAINT FK_MD_FORM_SECAO FOREIGN KEY
(
  FK_FORMULARIO 
)
REFERENCES MD_FORMULARIO
(
  ID_MD_FORMULARIO 
)
ENABLE;

ALTER TABLE TIPO_PROCESSAMENTO
ADD CONSTRAINT FK_TIPO_PROC_CONFIG_AVISO FOREIGN KEY
(
  CONFIG_AVISO_ID 
)
REFERENCES CAD_CONFIG_AVISO
(
  ID_CONFIG_AVISO 
)
ENABLE;
